// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ-qY1nDDd-oFwkz8lE3UJQ9zuv1rgPZM',
    appId: '1:1674333831:android:9bc7a91de05248266db222',
    messagingSenderId: '1674333831',
    projectId: 'dreith-985ec',
    storageBucket: 'dreith-985ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBinwSnEnzyl1c7onZhjxn1ChF5jIcGk4',
    appId: '1:1674333831:ios:c509146f77fff7646db222',
    messagingSenderId: '1674333831',
    projectId: 'dreith-985ec',
    storageBucket: 'dreith-985ec.firebasestorage.app',
    androidClientId: '1674333831-sbep3hs0k2r17h3fpq1v0qn33g91l687.apps.googleusercontent.com',
    iosClientId: '1674333831-5vq1dp73qo31h311l68dkrmgvcs7h6du.apps.googleusercontent.com',
    iosBundleId: 'com.example.dreith',
  );
}
